export const SocketEventsName = {
  NOTIFICATION: "NOTIFICATION",
  GET_COUNT_NOTIFICATION: "GET_COUNT_NOTIFICATION",
  REQUEST_COUNT_NOTIFICATION: "REQUEST_COUNT_NOTIFICATION",
  REQUEST_PAYMENT_RESPONSE: "REQUEST_PAYMENT_RESPONSE",
};
